plugins:
  poll_ui_enabled:
    default: true
    client: true
  poll_ui_provide_answers:
    default: false
    client: true
  template_manager_enabled:
    default: true
    client: true
  template_manager_provide_answers:
    default: false
    client: true
  template_manager_template:
    default: "This is a default template"
    client: "This is a client"
