plugins:
  template_manager_enabled:
    default: true
    client: true
  template_manager_one:
    default: 'regular:This is a regular message|stupid:This is stupid.|one:1111|two:222'
    client: true
